### ISSUE TITLE
Need more example.

### ISSUE THREAD

**Issue by ruoleng** [MetGang/TccWrapper#2]
Hi, Can you give more example of TccWrapper?
I try to use  'RegisterMethod' ， it seems  can complie  ,but will not run correctly ( certainly! without an instance  will cause exception)
Code like this:

```cpp
class A
{
public:
   int GetValue();
private:
    int  i;
}

std::optional<tw::TccWrapper> optTccWraper = tw::TccWrapper::WithOptContext();
optTccWraper->RegisterMethod<&A::GetValue>("GetValue");    //This can complie well

const char ccc[] = R"(
extern int GetValue();
int Test()
{
 return GetValue(); 
};
)";

optTccWraper->AddSourceCode(ccc);
optTccWraper->Compile();
int  i = optTccWraper->Call<int>("Test"); 

```
Environment  :
Windows10
Visual studio 2019

I think like std::bind , It need class instance . 
Can you give me an example ?

**Comment by MetGang** [comment]
Thanks for pointing out and sorry for late response. I need to look more often into that repository for sure. Here is full example for current problem.

```cpp
#include <iostream>

#include <TccWrapper.hpp>

class A
{
public:

    int GetValue() { return i; }

    int i;
};

int main()
{
    auto wrapper = tw::TccWrapper::WithOptContext();

    auto a = A{ 42 };

    wrapper->AddSymbol("a", &a);
    wrapper->RegisterMethod<&A::GetValue>("GetValue");

    const char code[] = R"(
extern int GetValue(void*);

int Test()
{
    extern __declspec(dllimport) void* a;

    return GetValue(&a); 
};
)";

    wrapper->AddSourceCode(code);
    wrapper->Compile();

    int i = wrapper->Call<int>("Test");

    std::cout << i << '\n';
}
```

Notes/explanation:

- When you register a method you actually register it as free function where the first argument is a pointer to the instance of class from which method is taken. Therefore `int A::GetValue()` is registered as `int GetValue(A*)` since this is the most logical way to handle methods in C. Thus `extern int GetValue(void*);` in script.
- To use methods you need also add pointer to the class instance as symbol. Thus `wrapper->AddSymbol("a", &a);` to add it and `extern __declspec(dllimport) void* a;` to import that symbol in script.
- `__declspec(dllimport)` part is needed only for Windows

I hope it was helpful. If you have more questions, please do not hesitate to ask.

I will add more complete examples in free time and keep issue open.

**Comment by ruoleng** [comment]
> Thanks for pointing out and sorry for late response. I need to look more often into that repository for sure. Here is full example for current problem.
> 
> ```c++
> #include <iostream>
> 
> #include <TccWrapper.hpp>
> 
> class A
> {
> public:
> 
>     int GetValue() { return i; }
> 
>     int i;
> };
> 
> int main()
> {
>     auto wrapper = tw::TccWrapper::WithOptContext();
> 
>     auto a = A{ 42 };
> 
>     wrapper->AddSymbol("a", &a);
>     wrapper->RegisterMethod<&A::GetValue>("GetValue");
> 
>     const char code[] = R"(
> extern int GetValue(void*);
> 
> int Test()
> {
>     extern __declspec(dllimport) void* a;
> 
>     return GetValue(&a); 
> };
> )";
> 
>     wrapper->AddSourceCode(code);
>     wrapper->Compile();
> 
>     int i = wrapper->Call<int>("Test");
> 
>     std::cout << i << '\n';
> }
> ```
> 
> Notes/explanation:
> 
> * When you register a method you actually register it as free function where the first argument is a pointer to the instance of class from which method is taken. Therefore `int A::GetValue()` is registered as `int GetValue(A*)` since this is the most logical way to handle methods in C. Thus `extern int GetValue(void*);` in script.
> * To use methods you need also add pointer to the class instance as symbol. Thus `wrapper->AddSymbol("a", &a);` to add it and `extern __declspec(dllimport) void* a;` to import that symbol in script.
> * `__declspec(dllimport)` part is needed only for Windows
> 
> I hope it was helpful. If you have more questions, please do not hesitate to ask.
> 
> I will add more complete examples in free time and keep issue open.

Thank you very much.  
TccWrapper is very useful .
